/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;


import estrutura.Regras;
import estrutura.Campo;
import javax.swing.JOptionPane;
import jogadores.Player;
import util.AudioInterface;
import util.Logger;

/**
 *
 * @author AFONSO
 */
public final class Jogo extends javax.swing.JFrame {

    private final Campo campo;
    private final Player player;
    private final Regras regras;
    private final Logger log;

    /**
     * Creates new form Janela
     *
     * @param campo
     * @param player
     * @param regras
     */
    public Jogo(Campo campo, Player player) {
        this.setResizable(false);
        this.log = new Logger(Jogo.class);
        initComponents();
        this.campo = campo;
        this.player = player;
        this.regras = new Regras(campo);
        atualizaLabelClass();
        atualizaCampo();
        this.regras.iniciaRodada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPropriedade = new javax.swing.JPanel();
        jLClass = new javax.swing.JLabel();
        jLVezAtual = new javax.swing.JLabel();
        jPQuadro = new javax.swing.JPanel();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jBVerRodadas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLClass.setText("jLabel1");

        jLVezAtual.setText("jLabel1");

        javax.swing.GroupLayout jPPropriedadeLayout = new javax.swing.GroupLayout(jPPropriedade);
        jPPropriedade.setLayout(jPPropriedadeLayout);
        jPPropriedadeLayout.setHorizontalGroup(
            jPPropriedadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPropriedadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLVezAtual)
                .addGap(30, 30, 30))
        );
        jPPropriedadeLayout.setVerticalGroup(
            jPPropriedadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPropriedadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPropriedadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLClass)
                    .addComponent(jLVezAtual))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jB1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jB2.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jB3.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });

        jB6.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });

        jB5.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });

        jB4.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });

        jB9.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });

        jB8.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });

        jB7.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });

        jBVerRodadas.setText("Ver Rodadas");
        jBVerRodadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerRodadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPQuadroLayout = new javax.swing.GroupLayout(jPQuadro);
        jPQuadro.setLayout(jPQuadroLayout);
        jPQuadroLayout.setHorizontalGroup(
            jPQuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPQuadroLayout.createSequentialGroup()
                .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPQuadroLayout.createSequentialGroup()
                .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPQuadroLayout.createSequentialGroup()
                .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jBVerRodadas)
        );
        jPQuadroLayout.setVerticalGroup(
            jPQuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPQuadroLayout.createSequentialGroup()
                .addGroup(jPQuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPQuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPQuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPQuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBVerRodadas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPropriedade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPQuadro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPPropriedade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPQuadro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        realizarJogada(1);
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        realizarJogada(2);
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        realizarJogada(3);
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        realizarJogada(4);
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        realizarJogada(5);
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        realizarJogada(6);
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        realizarJogada(7);
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
        realizarJogada(8);
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
        realizarJogada(9);
    }//GEN-LAST:event_jB9ActionPerformed

    private void jBVerRodadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerRodadasActionPerformed
        verRodadas();
    }//GEN-LAST:event_jBVerRodadasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBVerRodadas;
    private javax.swing.JLabel jLClass;
    private javax.swing.JLabel jLVezAtual;
    private javax.swing.JPanel jPPropriedade;
    private javax.swing.JPanel jPQuadro;
    // End of variables declaration//GEN-END:variables

    public void atualizaCampo() {
        try {
            desenhaCampo();
            atualizaLabelVezAtual();
            getWinner();
        } catch (Exception ex) {
            log.err(ex);
        }
    }

    private void desenhaCampo() throws Exception {
        jB1.setText(String.valueOf(campo.getPosicao(1)));
        jB2.setText(String.valueOf(campo.getPosicao(2)));
        jB3.setText(String.valueOf(campo.getPosicao(3)));
        jB4.setText(String.valueOf(campo.getPosicao(4)));
        jB5.setText(String.valueOf(campo.getPosicao(5)));
        jB6.setText(String.valueOf(campo.getPosicao(6)));
        jB7.setText(String.valueOf(campo.getPosicao(7)));
        jB8.setText(String.valueOf(campo.getPosicao(8)));
        jB9.setText(String.valueOf(campo.getPosicao(9)));
    }

    private void atualizaLabelVezAtual() {
        jLVezAtual.setText(String.valueOf(player.isVezAtual() ? "É a sua vez" : "Vez do oponente"));
        jLVezAtual.setText(player.getOpcao().name()+" - "+jLVezAtual.getText());
    }

    private void realizarJogada(int i) {
        try {
            if (player.isVezAtual() && regras.isJogadaValida(i)) {
                player.realizarJogada(i);
                atualizaCampo();
                AudioInterface.startAudioTeclaUp();
            }else{
                AudioInterface.startAudioTeclaDown();
            }
        } catch (Exception ex) {
            log.errClient(ex);
        }
    }

    private void atualizaLabelClass() {
        jLClass.setText(this.player.getClass().getSimpleName());
    }

    private void getWinner() throws Exception {
        if (regras.isWinner()) {
            log.infClient("O ganhador é o " + regras.getWinner());
            regras.finalizarRodada();
            regras.reiniciarJogo();
            isFimDeJogo();
            regras.iniciaRodada();
            atualizaCampo();
        }

        if (regras.isVelha()) {
            log.infClient("Deu Velha");
            regras.finalizarRodada();
            regras.reiniciarJogo();
            isFimDeJogo();
            regras.iniciaRodada();
            atualizaCampo();
        }
    }

    private void verRodadas() {
        JOptionPane.showMessageDialog(this, this.regras.verRodadas());
    }

    private void isFimDeJogo() {
        if (regras.isFimDeJogo()){
            log.infClient("O Jogo Terminou");
            verRodadas();
            regras.reiniciarJogoCompleto();
        }
    }

}
